### ISSUE TITLE
[Suggestion]  Make this client also support mathax client (A meteor fork)

### ISSUE THREAD

**Issue by FeminineFemale** [white-devil42/Atomic-with-meteor-support#2]
https://mathaxclient.xyz/ or https://github.com/MatHax/Client because currently, it says something about a resource pack then crashes

**Comment by white-devil42** [comment]
will try

**Comment by white-devil42** [comment]
does this client have any modules that meteor, atomic or wurst dont have? @FeminineFemale

**Comment by white-devil42** [comment]
fixed
